export * from "./home";
export * from "./login";
export * from "./register";
export * from "./asgmt";
export * from "./resultList";
export * from "./operation";
export * from "./resultStudent";
export * from "./subject";
export * from "./sendLink";
export * from './passwordReset'
export * from './user'
export * from './whiteList'
export * from './resultDetail'
